# Generated by Django 3.1.3 on 2021-07-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('cachorro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cachorro', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=2)),
                ('escolha_sexo', models.CharField(max_length=100)),
                ('tamanho_cachorro', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=50)),
                ('cor_pelagem', models.CharField(max_length=20)),
                ('info_cachorro', models.CharField(max_length=500)),
                ('nome_dono', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=75)),
                ('telefone', models.CharField(max_length=14)),
                ('imagem_focinho', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
    ]
