# Generated by Django 3.1.3 on 2021-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='cor_pelagem',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='info',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='escolha_sexo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='idade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='info',
            name='imagem_focinho',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='info_cachorro',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='nome_dono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='raca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='tamanho_cachorro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='telefone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
