# Generated by Django 3.1.3 on 2021-06-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('nome_cachorro', models.CharField(max_length=100)),
                ('cachorro_id', models.AutoField(primary_key=True, serialize=False)),
                ('idade', models.CharField(max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('raca', models.CharField(max_length=50)),
                ('cor_pelagem', models.CharField(max_length=20)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('info_cachorro', models.CharField(max_length=500)),
                ('nome_dono', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=75)),
                ('telefone', models.CharField(max_length=14)),
                ('imagem_focinho', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
    ]
